name: LoginQueue2Online
version: '${project.version}'
main: top.mcocet.loginqueue2online.LoginQueue2Online
api-version: '1.19'
folia-supported: true
commands:
  connect:
    description: 连接到指定服务器
    usage: /connect <服务器名> [玩家名]
    permission: loginqueue2online.connect
    permission-message: §c你没有权限使用此指令。
permissions:
  loginqueue2online.connect:
    description: 允许使用 /connect 指令
    default: true
  loginqueue2online.connect.others:
    description: 允许使用 /connect 指令指定其他玩家
    default: op
